AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Include:
    - '**/*.rake'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/lib/**/*.rb'
    - '**/spec/**/*.rb'
  Exclude:
    - '**/*.gemspec'
    - '**/Gemfile*'
    - '**/spec/schemas/**/*.rb'

Security/Eval:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/support/compare.rb'

Metrics/ClassLength:
  Max: 140

Style/RaiseArgs:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  Enabled: false

Style/SignalException:
  Enabled: false

Naming/VariableName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 9
  Exclude:
    - 'spec/support/compare.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8
  Exclude:
    - 'spec/support/compare.rb'

Metrics/AbcSize:
  Enabled: true
  Max: 30

Style/OptionalBooleanParameter:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

# New cops
Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/SwapValues:
  Enabled: true

Security/MarshalLoad:
  Enabled: false
